version: '3.6'
services:

  consignment-service:
    build: ./consignment-service
    image: consignment-service
    ports:
      - 50051:50051
      - 8081:8081
    environment:
      GRPC_PORT: ":50051"
      DISABLE_AUTH: "false"
      DB_HOST: "mongodb://datastore:27017"
      VESSEL_HOST: "vessel-service:50051"
      USER_HOST: "user-service:50051"
    depends_on: 
      - datastore
      - vessel-service
      - user-service

  vessel-service:
    build: ./consignment-service
    image: vessel-service
    ports:
      - 50052:50051
    environment:
      GRPC_PORT: ":50051"
      DB_HOST: "mongodb://datastore:27017"
    depends_on: 
      - datastore

  datastore:
    image: mongo:4.0
    ports: 
      - 27017:27017

  user-service:
    build: ./user-service
    image: user-service
    ports:
      - 50053:50051
      - 8080:8080
    environment:
      GRPC_PORT: ":50051"
      DB_HOST: "database"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on: 
      - database

  database:
    image: postgres:11-alpine
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client-cli:
    build: ./client-cli
    image: client-cli
    environment:
      USER_HOST: "user-service:50051"
      CONSIGMENT_HOST: "consignment-service:50051"
    depends_on: 
      - user-service
      - consignment-service