version: '3.1'
services:

  consignment-cli:
    build: ./consignment-cli
    image: consignment-cli

  consignment-service:
    build: ./consignment-service
    image: consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"

  vessel-service:
    build: ./consignment-service
    image: vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"