# Golang Build stage 
FROM golang:alpine as builder

ENV GO111MODULE=on
RUN apk --no-cache add git
WORKDIR /src/go/github.com/ragul28/grpc-ms/consignment-service

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

# Final stage - binary   
FROM alpine:latest

RUN mkdir /app
WORKDIR /app
COPY --from=builder /src/go/github.com/ragul28/grpc-ms/consignment-service .

CMD ["./consignment-service"]
EXPOSE 50051